import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import WholeContext from "./WholeContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gamify your study space!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WholeContext >
        {children}
        </WholeContext>
        </body>
    </html>
  );
}
